import { defineConfig } from 'vite';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { copyFileSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Minimal .env loader — reads KEY=VALUE lines, ignores comments/blanks.
function loadEnv() {
  const envPath = resolve(__dirname, '.env');
  const env = {};
  if (!existsSync(envPath)) return env;
  const raw = readFileSync(envPath, 'utf8');
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    // Strip surrounding quotes if present
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

export default defineConfig({
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    target: 'chrome110',
    minify: false,
    lib: {
      entry: resolve(__dirname, 'src/content.js'),
      formats: ['iife'],
      name: 'CustomCanvas',
      fileName: () => 'content.js',
    },
    rollupOptions: {
      output: {
        extend: true,
        inlineDynamicImports: true,
      },
    },
  },
  plugins: [
    {
      name: 'copy-static-assets',
      closeBundle() {
        const env = loadEnv();
        const clientId = env.GCAL_CLIENT_ID || '';
        if (!clientId || clientId.startsWith('YOUR_')) {
          console.warn(
            '[custom-canvas] GCAL_CLIENT_ID missing or placeholder in .env — ' +
            'Google Calendar integration will not work until you set it.'
          );
        }

        copyFileSync(
          resolve(__dirname, 'manifest.json'),
          resolve(__dirname, 'dist/manifest.json')
        );
        copyFileSync(
          resolve(__dirname, 'src/content.css'),
          resolve(__dirname, 'dist/content.css')
        );

        // background.js: substitute __GCAL_CLIENT_ID__ placeholder at copy time.
        const bgSrc = readFileSync(
          resolve(__dirname, 'src/background.js'),
          'utf8'
        );
        const bgOut = bgSrc.replace(/__GCAL_CLIENT_ID__/g, clientId);
        writeFileSync(resolve(__dirname, 'dist/background.js'), bgOut);

        // Extension icons. manifest.json points at icons/icon{16,32,48,128}.png;
        // those are generated by `npm run gen:icons` from logo/icon-filled.svg
        // and live in logo/. Mirror them into dist/icons/ so the unpacked
        // build has everything it needs without referencing a sibling folder.
        const iconsOutDir = resolve(__dirname, 'dist/icons');
        mkdirSync(iconsOutDir, { recursive: true });
        for (const size of [16, 32, 48, 128]) {
          const src = resolve(__dirname, `logo/icon${size}.png`);
          if (!existsSync(src)) {
            console.warn(
              `[custom-canvas] missing logo/icon${size}.png — run \`npm run gen:icons\` ` +
              `to generate it before building. Manifest references this path.`
            );
            continue;
          }
          copyFileSync(src, resolve(iconsOutDir, `icon${size}.png`));
        }
      },
    },
  ],
});
